### PR TITLE
Proxy Support

### PR DESCRIPTION
**Pull request by bigcat88**
Good day.

I would like to add proxy support to this node, since not all countries have a free subscription for Gemini Flash.

I also added support for the `GOOGLE_API_KEY` variable so that the key could be set through the environment variable.

_The action is backward compatible and should not disrupt anything for those who are already using this node in Workflows._
_I did not change any logic with "config.json" to make it easier to review._

I hope this is useful to someone :)

image

And thanks for this ComfyUI Node.

### CODE REVIEW

**Comment by bigcat88** [comment]
I can revert the changes to `.gitattributes` if needed so this PR does not rewrite each line(but usually in projects in which devs use different OSes it is present and have such value)

**Comment by ShmuelRonen** [comment]
Thanks for this support. tell me more about the proxy option from the user view.

**Comment by bigcat88** [comment]
In some countries there is Free use for the Flash model, and in some it is only available by billing.

After taking a VPS for $4 from DigitalOcean in USA NY(or in India) and in a couple of commands installing [squid](https://www.digitalocean.com/community/tutorials/how-to-set-up-squid-proxy-on-ubuntu-20-04) proxy there this allows to use this Gemini from a part of Europe where Google Gemini Flash is available only by billing.

This was made specifically as a parameter to make workflows with this node easier to deploy remotely and use, since installing this globally is not entirely convenient when you have several Comfis running in the same system in parallel, and processing requests from different users, each of whom has not only their own API key but also a proxy.

**Comment by ShmuelRonen** [comment]
Thanks. I will accept your code as a part of Gemini-Flash node.
I need from you an instruction adding to the README.md that guide user about this add on.

**Comment by bigcat88** [comment]
done

**Comment by ShmuelRonen** [comment]
Thanks!

**Pull request merged**
